export const SITE_TITLE = "Hallstrom Blog";
export const TEST_CONSTANT = "Hallstrom Blog";

export const NAVIGRAPH_POSTS = [
  {
    title: "Uncovering next version of Charts",
    slug: "uncovering-next-version-of-charts",
    tags: ["news", "new product", "charts"],
    date: "2016-10-18",
    excerpt:
      "We are kicking off this developer blog in a grand way by announcing the biggest piece of news since ever in the history of Navigraph: For over a year now we have been working in stealth mode to completely relaunch the Charts product line. The next version of Charts, scheduled for launch early 2017, will include new clients for phones and tablets (iOS and Android), new desktop clients (Windows and Mac), and a new web browser client.Not only are we covering more devices than ever, we have also included a lot of new functionality. Over the next few weeks we",
    author: "Navigraph Team",
    authorImage: "https://navigraph.com/assets/images/navigraph_logo_only.svg",
    readingTime: 1,
  },
  {
    title: "X-Plane 11 Ships with Navigraph as Default Dataset",
    slug: "x-plane-11-ships-with-navigraph-as-default-dataset",
    tags: ["news fmsdata xplane11"],
    date: "2016-10-21",
    excerpt:
      "X-Plane 11 is expected out any day now. We are all eager to see what the new user interface looks like; experience the new effects; the European autogen scenery; and also see what has been done in the IFR department. Of particular interest to us here at Navigraph is that X-Plane 11 will be using one single navigational database. Instead of many databases feeding different functions and addons, like in the case of some other flight simulation software, X-Plane 11 will have one single database used for scenery, map, ATC, AI and the GPS/FMS. If you would like",
    author: "Navigraph Team",
    authorImage: "https://navigraph.com/assets/images/navigraph_logo_only.svg",
    readingTime: 1,
  },
  {
    title: "Dynamic and Interactive Enroute Charts",
    slug: "dynamic-and-interactive-enroute-charts",
    tags: ["charts", "enroute charts", "news", "preview"],
    date: "2016-10-24",
    excerpt:
      "Enroute charts in printed form are big and unruly; covers the entire working surface of your average desk; flaps around the cockpit and won’t fold back to its original pocket size. By its size factor alone we can all agree that enroute charts are much more manageable in a digital form. In Navigraph Charts, you can easily zoom in and out of an area of interest using the pinch zoom gesture on tablets and the scroll wheel on a mouse. That’s fine, but in the next version of Charts we are taking digital enroute charts a few steps further in",
    author: "Navigraph Team",
    authorImage: "https://navigraph.com/assets/images/navigraph_logo_only.svg",
    readingTime: 7,
  },
  {
    title: "Charts - a Creative Process",
    slug: "charts-a-creative-process",
    tags: null,
    date: "2017-01-02",
    excerpt:
      " About two months ago, we announced the relaunch of the entire Charts product line. We are very excited about this and would like to show you the fruit of our labor right now, immediately, but developing these things take time. The work, the discussions, and the exchange of ideas leading up to this product launch have been going on for more than a year. In this post, we hope to give you an insight into the creative process of the new Charts product. By looking at the early sketches and reading between the lines you might be able to",
    author: "Navigraph Team",
    authorImage: "https://navigraph.com/assets/images/navigraph_logo_only.svg",
    readingTime: 10,
  },
  {
    title: "It’s named Charts Cloud for a reason",
    slug: "its-named-charts-cloud-for-a-reason",
    tags: null,
    date: "2017-02-10",
    excerpt:
      "In the new version of Charts Cloud you will see a completely dynamic and interactive enroute chart. We think you will like this, for many reasons, but mainly because it is completely searchable and also automatically declutters as you zoom in and out. We just experimented with the Frankfurt area, and we dare to say it’s good. Really good!You can also use the enroute charts to display your flights. In the photo below you can see a flight from WSSS to VTBS using the night mode version charts. More importantly - you might notice that this is all shown in",
    author: "Navigraph Team",
    authorImage: "https://navigraph.com/assets/images/navigraph_logo_only.svg",
    readingTime: 3,
  },
  {
    title: "Jeppesen Charts to the Flight Simulation Community",
    slug: "jeppesen-charts-to-the-flight-simulation-community",
    tags: null,
    date: "2017-02-22",
    excerpt:
      "Here at Navigraph we have been deliberately secretive about our upcoming charts product, and only presented a few of the new features. However, as we are approaching launch date, and still have some more features to show, we are now ready to unveil the greatest improvement to Navigraph Charts to date: In the next version of Navigraph Charts, all chart data will be provided by Jeppesen.imageEnhanced SID and STAR Chart FormatThe new version of Navigraph Charts will display Jeppesen’s new and enhanced SID and STAR chart format featuring, among other things, colored topography and true-to-scale depiction.",
    author: "Navigraph Team",
    authorImage: "https://navigraph.com/assets/images/navigraph_logo_only.svg",
    readingTime: 3,
  },
  {
    title: "The Advanced Humor of Waypoint Names",
    slug: "the-advanced-humor-of-waypoint-names",
    tags: null,
    date: "2017-03-24",
    excerpt:
      "It is a very subtle form of artistry but it will almost certainly blow your mind - if you are in the know, that is! Otherwise you don’t know, and, well, then you don’t know, and your mind will remain unblown. Let us just say this: When our team was going through the new charts for the next cycle someone actually uttered the words “Could it be…? Nooo, it can’t be!” However, before we reveal this gem, let’s start with the basics and slowly build up to what must be considered a modern day masterpiece.So you know when you plan",
    author: "Navigraph Team",
    authorImage: "https://navigraph.com/assets/images/navigraph_logo_only.svg",
    readingTime: 3,
  },
  {
    title: "Test 1 2. Is this thing on?",
    slug: "test-1-2-is-this-thing-on",
    tags: null,
    date: "2017-04-20",
    excerpt:
      "Charts Cloud, our browser based chart viewer, and Charts Android, the app for Android tablets, are now out the door and in the process of being beta tested by a team of invited hardcore and tenacious simmers. Using TestFairy reports and automated log data are trickling in to our office and one by one we are exterminating the final bugs. The Android app just passed 1,000 logged beta testing sessions over a total of 122 man hours.We are really pleased with our initial design decision to make significant parts of the applications web-based. Everything related to the enroute charts",
    author: "Navigraph Team",
    authorImage: "https://navigraph.com/assets/images/navigraph_logo_only.svg",
    readingTime: 5,
  },
  {
    title: "New Ideas",
    slug: "new-ideas",
    tags: null,
    date: "2017-09-16",
    excerpt:
      "If you were to walk down the street in Old Town Stockholm were Navigraph has it’s offices you would see that the big windows facing the street now have lots and lots of small colorful notes arranged in rows and columns according to some indecipherable system. On each of these notes there is new creative idea for how to develop the flight simulation community and give Navigraph users more useful software. These bright neon clusters of PostIts is the output of the last two days of workshop held by the Navigraph Team.It has been little over a month since Navigraph",
    author: "Navigraph Team",
    authorImage: "https://navigraph.com/assets/images/navigraph_logo_only.svg",
    readingTime: 4,
  },
  {
    title: "Survey Results: Prepar3D & X-Plane up, FSX down",
    slug: "survey-results-prepar3d-x-plane-up-fsx-down",
    tags: null,
    date: "2017-10-14",
    excerpt:
      "The Navigraph FlightSim Community Survey 2017 conducted between 20th October and 6th of November has now been compiled and partially analyzed. This year 3,187 respondents participated, which is an improvement over last year’s 2,200 participants.This blog posts highlights some interesting and notable observations in the survey. What’s interesting and notable depends on the reader, but in general we can say that the average flight simmer is a 47 year old male living in the US, working full time, with an average of 16 years of flight simulation experience, flying a Lockheed Martin Prepar3D v.4, mainly out of interest, about five",
    author: "Navigraph Team",
    authorImage: "https://navigraph.com/assets/images/navigraph_logo_only.svg",
    readingTime: 7,
  },
  {
    title: "November",
    slug: "november",
    tags: null,
    date: "2017-11-07",
    excerpt:
      "November has been a busy month for Navigraph. It included a workshop and a customer survey with the subsequent post processing of ideas and data. We are set with great development ideas for several months to come. Planning for the longer perspective takes resources, and as such it is an investment in a way, but we were of course also able to complete some of our planned development for this month as well. However, another topic that has consumed a lot of our efforts this month is the investigation and remedy of the November 1st incident when our login servers",
    author: "Navigraph Team",
    authorImage: "https://navigraph.com/assets/images/navigraph_logo_only.svg",
    readingTime: 4,
  },
  {
    title: "FlightSim Community Survey 2018 Results",
    slug: "flightsim-community-survey-2018-results",
    tags: null,
    date: "2018-11-19",
    excerpt:
      "The typical flight simulator enthusiast is a 43 year old male from the United States. He flies simulators 2-3 times per week for about 5-10 hours in total and was introduced to flight simulation 20 year ago. There is a 27% likelihood he already has some sort of pilot license. If so, he was introduced to flight simulation before he pursued his pilot license. Moreover he has a bachelor’s degree, is full time employed, makes 50,000 USD per year before tax, and spends about 250 USD on software and 200 USD on hardware annually. He prefers X-Plane 11, but Prepar3D",
    author: "Navigraph Team",
    authorImage: "https://navigraph.com/assets/images/navigraph_logo_only.svg",
    readingTime: 4,
  },
  {
    title: "Meta Analysis of the Community Survey",
    slug: "meta-analysis-of-the-community-survey",
    tags: null,
    date: "2019-00-22",
    excerpt:
      "Once again we would like to thank all of you who participated to the survey (find it here). In the weeks that have passed since we published the results, we have read many comments and questions in various forums which we would like to address with this blog post.This post comments on questions like:What was the role of the partners?Why did we say “typical” and not “average” user?Was the survey representative?Was there any selection bias?Was the Survey Too Long?What was the role of the partners?Previous years we sent the survey link only to",
    author: "Navigraph Team",
    authorImage: "https://navigraph.com/assets/images/navigraph_logo_only.svg",
    readingTime: 6,
  },
  {
    title: "The Yearly Workshop",
    slug: "the-yearly-workshop",
    tags: null,
    date: "2019-08-20",
    excerpt:
      "Every year, sometime in fall, the Navigraph team huddles up in something we call the yearly workshop. This year we met a little earlier than previous years, because we wanted the meeting to serve also as a kickoff into our new projects. Now that version 7 of Navigraph Charts is released\\* we are ready to take on new projects.The workshop this year was preceded by many individual meetings trying to organize and prioritize our goals for the future. For the coming year, we have decided to focus on the following development.VFR ChartsIn addition to the existing IFR and CAO",
    author: "Navigraph Team",
    authorImage: "https://navigraph.com/assets/images/navigraph_logo_only.svg",
    readingTime: 5,
  },
  {
    title: "Jeppesen Visit",
    slug: "jeppesen-visit",
    tags: null,
    date: "2019-08-27",
    excerpt:
      "This week Magnus and Pontus flew to Frankfurt to meet with Jeppesen, a subsidiary of Boeing, to discuss data availability for the future VFR Charts product. While in Frankfurt, or Neu-Isenburg more precisely, Magnus and Pontus also visited the production line and the Digital Aviation & Analytics Lab.Boeing Experience CenterElrey Borge Jeppesen, an American aviation pioneer, whose parents were immigrants from Denmark, made significant contributions to the field of air navigation in that he developed manuals and charts that allowed pilots to fly much more safely. In 1934 he founded a company that bears his name. In",
    author: "Navigraph Team",
    authorImage: "https://navigraph.com/assets/images/navigraph_logo_only.svg",
    readingTime: 4,
  },
  {
    title: "FlightSim Community Survey 2019 Results",
    slug: "flightsim-community-survey-2019-results",
    tags: null,
    date: "2020-01-03",
    excerpt:
      "What is the most popular flight simulation software? How many are planning to get the upcoming Microsoft Flight Simulator? How much do flight simulator enthusiasts spend on hardware and software every year? These were some of the questions that we set out to answer in this year’s edition of the FlightSim Community Survey. The turnout was better than ever and we are very happy with the results.The survey consisted of 93 questions and covered demographics, relation to aviation, simulator habits, consumption habits, the simulator platform itself, some questions on media and community participation, and of course questions on aircraft and",
    author: "Navigraph Team",
    authorImage: "https://navigraph.com/assets/images/navigraph_logo_only.svg",
    readingTime: 7,
  },
  {
    title: "New Website",
    slug: "new-website",
    tags: null,
    date: "2020-06-16",
    excerpt:
      "imageHave you seen our new website? We have made some nice improvements over the previous one that we would like to show you.Your AccountFirst off - we have created a special area for you as a Navigraph user. You start by signing in via the button in the upper right corner using either your username like before or your email address. Being able to use both should make it easier to get in.In this special area we have gathered everything Navigraph users have access to - like download links to all of the software you can use: desktop",
    author: "Navigraph Team",
    authorImage: "https://navigraph.com/assets/images/navigraph_logo_only.svg",
    readingTime: 2,
  },
  {
    title: "Navigraph’s Plans for the new Microsoft Flight Simulator",
    slug: "navigraphs-plans-for-the-new-microsoft-flight-simulator",
    tags: null,
    date: "2020-07-13",
    excerpt:
      "What are Navigraph’s plans for the upcoming Microsoft Flight Simulator? How are Charts, NavData and Simlink used on the new platform? What is Navigraph’s vision on supporting addon developers in this new era? Magnus Axholt, CEO of Navigraph, provides some answers to these questions and more.In a few days the long anticipated Microsoft Flight Simulator will be released. Microsoft did a good job in building up the anticipation. Little by little the flightsim community was let in on the developments and this simulator looks nothing short of amazing! I think what first draws the user’s attention are the stunning visuals.",
    author: "Navigraph Team",
    authorImage: "https://navigraph.com/assets/images/navigraph_logo_only.svg",
    readingTime: 8,
  },
  {
    title: "FlightSim Community 2020 Survey Results",
    slug: "flightsim-community-2020-survey-results",
    tags: null,
    date: "2021-00-11",
    excerpt:
      "It’s that time of the year again when Navigraph releases the annual flight simulation community survey - and what a year it has been! There are three new flight simulators released: Lockheed Martin Prepar3D version 5 in April, Microsoft Flight Simulator 2020 in August, and Laminar Research X-Plane 11.50 in September. How have they been received so far? Which flight simulator platform is the most popular? Read on to find the complete report, the survey dataset and some highlights from the results. We had a fantastic turnout this year. In 2018 we had 15,000 respondents. Last year we had",
    author: "Navigraph Team",
    authorImage: "https://navigraph.com/assets/images/navigraph_logo_only.svg",
    readingTime: 8,
  },
  {
    title: "Navigraph Charts in Working Title Cessna Citation CJ4 for FS2020",
    slug: "navigraph-charts-in-working-title-cessna-citation-cj4-for-fs2020",
    tags: null,
    date: "2021-02-10",
    excerpt:
      "We are very excited to announce the first successful cockpit integration of Navigraph Charts in a Microsoft Flight Simulator 2020 in-game aircraft. You can now view Jeppesen charts inside the simulator and also follow along on procedures and during taxiing using the moving maps functionality. In this video, the Working Title developers Matt and Dominik, walk us through how the Charts interface works onboard the Cessna Citation CJ4\\.In this interview, Matt and Dominik from Working Title talk about the modifications they have made to the default Cessna Citation CJ4 aircraft in Microsoft Flight Simulator 2020\\. We here at Navigraph",
    author: "Navigraph Team",
    authorImage: "https://navigraph.com/assets/images/navigraph_logo_only.svg",
    readingTime: 4,
  },
  {
    title: "Navigraph acquires SimBrief",
    slug: "navigraph-acquires-simbrief",
    tags: null,
    date: "2021-02-31",
    excerpt:
      "Navigraph, the flight simulation community’s trusted source for updated charts and navigational data, today announced that it has acquired SimBrief, the flight simulation community’s most popular flight planning software.The acquisition is a natural progression of the already close collaboration between Navigraph and SimBrief. It builds on the integration between the two platforms existing since 2013 and provides the ability to do flight planning using up to date navigational data.SimBrief’s flight planning functionality will continue to be free. Users who want to use the most current navigational data can subscribe to Navigraph and unlock the AIRAC cycles in SimBrief,",
    author: "Navigraph Team",
    authorImage: "https://navigraph.com/assets/images/navigraph_logo_only.svg",
    readingTime: 2,
  },
  {
    title: "“NAV DATA OUT OF DATE”",
    slug: "nav-data-out-of-date",
    tags: [
      "msfs",
      "microsoft flight simulator",
      "flight sim",
      "flightsim",
      "flight simulator",
    ],
    date: "2021-08-03",
    excerpt:
      "imageIf you have encountered the “NAV DATA OUT OF DATE” message, or want to know how to get updated navdata for your flight simulators and add-ons, then you’re at the right place! Navigraph has provided the flight simulation community with navigational data since 2006\\. In this article we’ll explain how you can get your navdata up to date fast and easy.What is navdata?Navdata (also known as FMS Data) is a general purpose dataset used in a wide array of applications, ranging from flight planning systems to various navigational and performance systems onboard the aircraft. The data contains",
    author: "Navigraph Team",
    authorImage: "https://navigraph.com/assets/images/navigraph_logo_only.svg",
    readingTime: 3,
  },
  {
    title: "How to Update MSFS 2020 with Navigraph Navdata Center",
    slug: "how-to-update-msfs-2020-with-navigraph-navdata-center",
    tags: [
      "msfs2020",
      "msfs",
      "microsoft flight simulator",
      "flight simulator",
      "flightsim",
    ],
    date: "2021-08-03",
    excerpt:
      "imageNavigraph offers an update service for the navigational database in Microsoft Flight Simulator, also known as MSFS 2020\\. The service installs current navdata directly into your MSFS 2020 from the industry leading provider Jeppesen. In this article we’ll explain how you can get current and worldwide navdata for MSFS 2020 fast and easy.What is navdata?Navdata (also known as FMS Data) is a general purpose dataset used in a wide array of applications, ranging from flight planning systems to various navigational and performance systems onboard the aircraft. The data contains a massive amount of information to determine not",
    author: "Navigraph Team",
    authorImage: "https://navigraph.com/assets/images/navigraph_logo_only.svg",
    readingTime: 3,
  },
  {
    title:
      "How to View Navigraph Charts Inside Microsoft Flight Simulator 2020",
    slug: "how-to-view-navigraph-charts-inside-microsoft-flight-simulator-2020",
    tags: [
      "microsoft flight simulator",
      "msfs",
      "msfs2020",
      "flightsimulator",
      "flightsim",
    ],
    date: "2021-08-03",
    excerpt:
      "imageNavigraph is proud to offer the flight simulation community professional, worldwide, and updated airport/terminal charts from Jeppesen. The chart format is based on research by human factors specialists and subject matter experts, and is the real-world choice for many of the world’s airlines. The aim is to describe approach and departure procedures from airports with a clear presentation of altitudes, obstacles and landing minima during Instrument Flight Rules.The charts are accessible in our suite of apps, ranging from desktop and cloud versions to tablet apps through App Store and Google Play. Now the charts can also be accessed",
    author: "Navigraph Team",
    authorImage: "https://navigraph.com/assets/images/navigraph_logo_only.svg",
    readingTime: 3,
  },
  {
    title: "New Feature Additions to SimBrief",
    slug: "new-feature-additions-to-simbrief",
    tags: ["simbrief", "flight simulator", "flight sim"],
    date: "2021-08-09",
    excerpt:
      "imageSimBrief.com is our free, web-based, flight planning tool that produces accurate briefing packages for flight simulation. When creating a flight plan using SimBrief.com, a briefing package similar to those real-world pilots use will be generated. In this article, we will cover some of the latest feature additions to SimBrief that have been realized thanks to this posting in the Navigraph forum.Enroute and takeoff alternate range rings added to interactive mapA takeoff alternate airport is used if an aircraft would not be able to return to its departure airport shortly after takeoff. This would be required if the",
    author: "Navigraph Team",
    authorImage: "https://navigraph.com/assets/images/navigraph_logo_only.svg",
    readingTime: 2,
  },
  {
    title: "Cycle 2109 Is Out!",
    slug: "cycle-2109-is-out",
    tags: null,
    date: "2021-08-09",
    excerpt:
      "imageHey there! Navigraph CEO Magnus here! Summer is slowly turning into fall here in the northern hemisphere and the Navigraph team is returning back to office well energized after a much needed vacation. Today cycle 2109 goes into effect and we have prepared a fresh batch of updated navdata and charts for you. I also want to take this moment to give you a little update about what’s going on.AIRAC Cycle ChecklistEvery 28 days Navigraph releases new charts and updated navdata to the flight simulation community. Just like the rest of the aviation industry we follow the AIRAC",
    author: "Navigraph Team",
    authorImage: "https://navigraph.com/assets/images/navigraph_logo_only.svg",
    readingTime: 6,
  },
  {
    title: "Conventional Navigation in MSFS 2020: VOR and NDB Updates",
    slug: "conventional-navigation-in-msfs-2020-vor-and-ndb-updates",
    tags: [
      "msfs2020",
      "msfs",
      "microsoft flight simulator",
      "flight simulator",
      "flight sim",
    ],
    date: "2021-08-09",
    excerpt:
      "imageSince the release of PMDG DC-6 for MSFS 2020, we have seen an increasing demand for a complete and current database of VOR and NDB navaids. In particular, VOR flying has become increasingly popular within the flight simulation community. Conventional flying can also be practiced in some of the default aircraft types in MSFS, such as the Cessna 172 and the Bonanza G36\\. In this article, we’ll cover our recent navdata developments that have been made to facilitate flight simulation with conventional navigation.What is conventional navigation?Flights using conventional navigation have been conducted since the 1930s and",
    author: "Navigraph Team",
    authorImage: "https://navigraph.com/assets/images/navigraph_logo_only.svg",
    readingTime: 4,
  },
];
